export const estadosMunicipios: Record<string, string[]> = {
  'Aguascalientes': ['Aguascalientes', 'Asientos', 'Calvillo', 'Cosío', 'El Llano', 'Jesús María', 'Pabellón de Arteaga', 'Rincón de Romos', 'San Francisco de los Romo', 'San José de Gracia', 'Tepezalá'],
  'Baja California': ['Ensenada', 'Mexicali', 'Playas de Rosarito', 'Tecate', 'Tijuana'],
  'Baja California Sur': ['Comondú', 'La Paz', 'Loreto', 'Los Cabos', 'Mulegé'],
  'Campeche': ['Calkiní', 'Campeche', 'Candelaria', 'Carmen', 'Champotón', 'Escárcega', 'Hecelchakán', 'Hopelchén', 'Palizada', 'Tenabo'],
  'Chiapas': ['Acala', 'Altamirano', 'Chiapa de Corzo', 'Comitán de Domínguez', 'Ocosingo', 'Palenque', 'San Cristóbal de las Casas', 'Tapachula', 'Tonalá', 'Tuxtla Gutiérrez'],
  'Chihuahua': ['Camargo', 'Chihuahua', 'Cuauhtémoc', 'Delicias', 'Hidalgo del Parral', 'Jiménez', 'Juárez', 'Meoqui', 'Ojinaga', 'Saucillo'],
  'Ciudad de México': ['Álvaro Obregón', 'Azcapotzalco', 'Benito Juárez', 'Coyoacán', 'Cuajimalpa de Morelos', 'Cuauhtémoc', 'Gustavo A. Madero', 'Iztacalco', 'Iztapalapa', 'La Magdalena Contreras', 'Miguel Hidalgo', 'Milpa Alta', 'Tláhuac', 'Tlalpan', 'Venustiano Carranza', 'Xochimilco'],
  'Coahuila': ['Acuña', 'Monclova', 'Muzquiz', 'Piedras Negras', 'Ramos Arizpe', 'Sabinas', 'Saltillo', 'San Pedro', 'Torreón'],
  'Colima': ['Armería', 'Colima', 'Comala', 'Coquimatlán', 'Cuauhtémoc', 'Ixtlahuacán', 'Manzanillo', 'Minatitlán', 'Tecomán', 'Villa de Álvarez'],
  'Durango': ['Canatlán', 'Durango', 'El Salto', 'Gómez Palacio', 'Lerdo', 'Nombre de Dios', 'Nuevo Ideal', 'Pueblo Nuevo', 'San Dimas', 'Vicente Guerrero'],
  'Guanajuato': ['Celaya', 'Guanajuato', 'Irapuato', 'Lagos de Moreno', 'León', 'Pénjamo', 'Salamanca', 'Salvatierra', 'San Miguel de Allende', 'Silao'],
  'Guerrero': ['Acapulco de Juárez', 'Chilpancingo de los Bravo', 'Ciudad Altamirano', 'Iguala de la Independencia', 'Taxco de Alarcón', 'Zihuatanejo de Azueta'],
  'Hidalgo': ['Actopan', 'Pachuca de Soto', 'Tizayuca', 'Tula de Allende', 'Tulancingo de Bravo'],
  'Jalisco': ['Acatlán de Juárez', 'Ameca', 'Autlán de Navarro', 'El Salto', 'Guadalajara', 'Gudalajara', 'Lagos de Moreno', 'La Barca', 'Ocotlán', 'Puerto Vallarta', 'San Pedro Tlaquepaque', 'Sayula', 'Tepatitlán de Morelos', 'Tlajomulco de Zúñiga', 'Tlaquepaque', 'Tonalá', 'Zapopan', 'Zapotiltic', 'Zapotlanejo'],
  'Estado de México': ['Atizapán de Zaragoza', 'Coacalco de Berriozábal', 'Cuautitlán Izcalli', 'Ecatepec de Morelos', 'Naucalpan de Juárez', 'Netzahualcóyotl', 'Nicolás Romero', 'Tecámac', 'Tlalnepantla de Baz', 'Toluca', 'Tultitlán'],
  'Michoacán': ['Apatzingán', 'Hidalgo', 'Lázaro Cárdenas', 'Morelia', 'Pátzcuaro', 'Uruapan', 'Zamora', 'Zitácuaro'],
  'Morelos': ['Cuernavaca', 'Cuautla', 'Jiutepec', 'Temixco', 'Tepoztlán', 'Yautepec de Zaragoza'],
  'Nayarit': ['Bahía de Banderas', 'Compostela', 'Ixtlán del Río', 'Santiago Ixcuintla', 'Tecuala', 'Tepic', 'Tuxpan', 'Xalisco'],
  'Nuevo León': ['Apodaca', 'Cadereyta Jiménez', 'García', 'General Escobedo', 'Guadalupe', 'Juárez', 'Linares', 'Monterrey', 'Montemorelos', 'Salinas Victoria', 'San Nicolás de los Garza', 'San Pedro Garza García', 'Santa Catarina'],
  'Oaxaca': ['Huajuapan de León', 'Juchitán de Zaragoza', 'Oaxaca de Juárez', 'Ocotlán de Morelos', 'Puerto Escondido', 'Salina Cruz', 'Tehuantepec', 'Tuxtepec'],
  'Puebla': ['Atlixco', 'Cholula', 'Puebla', 'San Martín Texmelucan', 'Tehuacán', 'Teziutlán'],
  'Querétaro': ['Corregidora', 'El Marqués', 'Huimilpan', 'Jalpan de Serra', 'Pedro Escobedo', 'Querétaro', 'San Juan del Río', 'Tequisquiapan'],
  'Quintana Roo': ['Benito Juárez', 'Cozumel', 'Felipe Carrillo Puerto', 'Isla Mujeres', 'José María Morelos', 'Lázaro Cárdenas', 'Othón P. Blanco', 'Solidaridad', 'Tulum'],
  'San Luis Potosí': ['Ahualulco', 'Ciudad Valles', 'Matehuala', 'Rioverde', 'San Luis Potosí', 'Soledad de Graciano Sánchez'],
  'Sinaloa': ['Ahome', 'Culiacán', 'Guasave', 'Mazatlán', 'Navolato', 'Salvador Alvarado'],
  'Sonora': ['Agua Prieta', 'Cajeme', 'Guaymas', 'Hermosillo', 'Navojoa', 'Nogales', 'San Luis Río Colorado'],
  'Tabasco': ['Cárdenas', 'Centro', 'Comalcalco', 'Cunduacán', 'Huimanguillo', 'Macuspana', 'Paraíso'],
  'Tamaulipas': ['Altamira', 'Ciudad Madero', 'Ciudad Victoria', 'Matamoros', 'Nuevo Laredo', 'Reynosa', 'Tampico'],
  'Tlaxcala': ['Apizaco', 'Chiautempan', 'Huamantla', 'Tlaxcala', 'Zacatelco'],
  'Veracruz': ['Boca del Río', 'Coatzacoalcos', 'Córdoba', 'Minatitlán', 'Orizaba', 'Poza Rica de Hidalgo', 'Tuxpan', 'Veracruz', 'Xalapa'],
  'Yucatán': ['Kanasín', 'Mérida', 'Progreso', 'Tizimín', 'Umán', 'Valladolid'],
  'Zacatecas': ['Calera', 'Fresnillo', 'Guadalupe', 'Jerez', 'Loreto', 'Zacatecas'],
}

export const estados = Object.keys(estadosMunicipios).sort()