export const estadosMunicipios: Record<string, string[]> = {
  'Aguascalientes': [
    'Aguascalientes', 'Asientos', 'Calvillo', 'Cosío', 'El Llano',
    'Jesús María', 'Pabellón de Arteaga', 'Rincón de Romos',
    'San Francisco de los Romo', 'San José de Gracia', 'Tepezalá'
  ],
  'Baja California': [
    'Ensenada', 'Mexicali', 'Playas de Rosarito', 'Tecate', 'Tijuana',
    'San Quintín', 'San Felipe', 'Primo Tapia', 'Valle de Guadalupe'
  ],
  'Baja California Sur': [
    'Cabo San Lucas', 'Ciudad Constitución', 'Comondú', 'Guerrero Negro',
    'La Paz', 'Loreto', 'Los Cabos', 'Mulegé', 'San José del Cabo', 'Santa Rosalía'
  ],
  'Campeche': [
    'Calkiní', 'Campeche', 'Candelaria', 'Carmen', 'Champotón',
    'Ciudad del Carmen', 'Escárcega', 'Hecelchakán', 'Hopelchén',
    'Palizada', 'Sabancuy', 'Tenabo'
  ],
  'Chiapas': [
    'Arriaga', 'Berriozábal', 'Chiapa de Corzo', 'Chicomuselo', 'Cintalapa',
    'Comitán de Domínguez', 'Copainalá', 'El Bosque', 'Escuintla',
    'Frontera Comalapa', 'Huixtla', 'Ixtapa', 'Jiquipilas', 'Juárez',
    'La Concordia', 'La Trinitaria', 'Las Margaritas', 'Las Rosas',
    'Mapastepec', 'Motozintla', 'Ocosingo', 'Ocozocoautla de Espinosa',
    'Palenque', 'Pichucalco', 'Pijijiapan', 'Reforma', 'Salto de Agua',
    'San Cristóbal de las Casas', 'San Fernando', 'Simojovel',
    'Tapachula', 'Tecpatán', 'Tenejapa', 'Teopisca', 'Tila', 'Tonalá',
    'Tuxtla Chico', 'Tuxtla Gutiérrez', 'Tuzantán', 'Venustiano Carranza',
    'Villa Corzo', 'Villaflores', 'Yajalón', 'Zinacantán'
  ],
  'Chihuahua': [
    'Ahumada', 'Ascensión', 'Bocoyna', 'Buenaventura', 'Camargo',
    'Casas Grandes', 'Chihuahua', 'Cuauhtémoc', 'Delicias',
    'Gómez Farías', 'Guadalupe', 'Guadalupe y Calvo', 'Guachochi',
    'Guerrero', 'Hidalgo del Parral', 'Janos', 'Jiménez', 'Juárez',
    'Madera', 'Matamoros', 'Meoqui', 'Namiquipa', 'Nuevo Casas Grandes',
    'Ocampo', 'Ojinaga', 'Rosales', 'San Francisco del Oro',
    'Santa Bárbara', 'Saucillo', 'Temósachic', 'Urique'
  ],
  'Ciudad de México': [
    'Álvaro Obregón', 'Azcapotzalco', 'Benito Juárez', 'Coyoacán',
    'Cuajimalpa de Morelos', 'Cuauhtémoc', 'Gustavo A. Madero',
    'Iztacalco', 'Iztapalapa', 'La Magdalena Contreras', 'Miguel Hidalgo',
    'Milpa Alta', 'Tláhuac', 'Tlalpan', 'Venustiano Carranza', 'Xochimilco'
  ],
  'Coahuila': [
    'Acuña', 'Arteaga', 'Castaños', 'Cuatro Ciénegas', 'Francisco I. Madero',
    'Frontera', 'General Cepeda', 'Guerrero', 'Jiménez', 'Matamoros',
    'Monclova', 'Múzquiz', 'Nava', 'Parras', 'Piedras Negras',
    'Ramos Arizpe', 'Sabinas', 'Saltillo', 'San Buenaventura',
    'San Juan de Sabinas', 'San Pedro', 'Torreón', 'Viesca', 'Zaragoza'
  ],
  'Colima': [
    'Armería', 'Colima', 'Comala', 'Coquimatlán', 'Cuauhtémoc',
    'Ixtlahuacán', 'Manzanillo', 'Minatitlán', 'Tecomán', 'Villa de Álvarez'
  ],
  'Durango': [
    'Canatlán', 'Cuencamé', 'Durango', 'El Oro', 'Gómez Palacio',
    'Guadalupe Victoria', 'Guanaceví', 'Hidalgo', 'Lerdo', 'Mapimí',
    'Mezquital', 'Nombre de Dios', 'Nuevo Ideal', 'Ocampo',
    'Pánuco de Coronado', 'Pueblo Nuevo', 'Rodeo', 'San Dimas',
    'San Juan del Río', 'Santiago Papasquiaro', 'Tamazula',
    'Tepehuanes', 'Tlahualilo', 'Vicente Guerrero'
  ],
  'Guanajuato': [
    'Abasolo', 'Acámbaro', 'Apaseo el Alto', 'Apaseo el Grande',
    'Celaya', 'Comonfort', 'Cortazar', 'Cuerámaro', 'Dolores Hidalgo',
    'Guanajuato', 'Irapuato', 'Jaral del Progreso', 'Lagos de Moreno',
    'León', 'Manuel Doblado', 'Moroleón', 'Pénjamo', 'Purísima del Rincón',
    'Romita', 'Salamanca', 'Salvatierra', 'San Diego de la Unión',
    'San Felipe', 'San Francisco del Rincón', 'San José Iturbide',
    'San Luis de la Paz', 'San Miguel de Allende', 'Santa Cruz de Juventino Rosas',
    'Santiago Maravatío', 'Silao', 'Uriangato', 'Valle de Santiago',
    'Villagrán', 'Yuriria'
  ],
  'Guerrero': [
    'Acapulco de Juárez', 'Ahuacuotzingo', 'Ajuchitlán del Progreso',
    'Alcozauca de Guerrero', 'Alpoyeca', 'Apaxtla', 'Arcelia',
    'Atenango del Río', 'Atlamajalcingo del Monte', 'Atlixtac',
    'Atoyac de Álvarez', 'Ayutla de los Libres', 'Azoyú',
    'Benito Juárez', 'Buenavista de Cuéllar', 'Chilapa de Álvarez',
    'Chilpancingo de los Bravo', 'Coahuayutla de José María Izazaga',
    'Cocula', 'Copala', 'Copalillo', 'Copanatoyac', 'Coyuca de Benítez',
    'Coyuca de Catalán', 'Cuajinicuilapa', 'Cualác', 'Cuautepec',
    'Cuetzala del Progreso', 'Cutzamala de Pinzón', 'Eduardo Neri',
    'Florencio Villarreal', 'General Canuto A. Neri', 'General Heliodoro Castillo',
    'Huamuxtitlán', 'Huitzuco de los Figueroa', 'Iguala de la Independencia',
    'Igualapa', 'Ixcateopan de Cuauhtémoc', 'José Joaquín de Herrera',
    'Juan R. Escudero', 'Juchitán', 'La Unión de Isidoro Montes de Oca',
    'Leonardo Bravo', 'Malinaltepec', 'Marquelia', 'Mártir de Cuilapan',
    'Metlatónoc', 'Mochitlán', 'Olinalá', 'Ometepec', 'Pedro Ascencio Alquisiras',
    'Petatlán', 'Pilcaya', 'Pungarabato', 'Quechultenango', 'San Luis Acatlán',
    'San Marcos', 'San Miguel Totolapan', 'Taxco de Alarcón', 'Tecoanapa',
    'Técpan de Galeana', 'Teloloapan', 'Tepecoacuilco de Trujano',
    'Tetipac', 'Tixtla de Guerrero', 'Tlacoachistlahuaca', 'Tlacoapa',
    'Tlalchapa', 'Tlalixtaquilla de Maldonado', 'Tlapa de Comonfort',
    'Tlapehuala', 'Xalpatláhuac', 'Xochihuehuetlán', 'Xochistlahuaca',
    'Zapotitlán Tablas', 'Zihuatanejo de Azueta', 'Zirándaro', 'Zitlala'
  ],
'Hidalgo': [
    'Acatlán', 'Acaxochitlán', 'Actopan', 'Ajacuba', 'Alfajayucan',
    'Apan', 'Atitalaquia', 'Atotonilco de Tula', 'Atotonilco el Grande',
    'Cardonal', 'Chapantongo', 'Cuautepec de Hinojosa', 'El Arenal',
    'Emiliano Zapata', 'Epazoyucan', 'Francisco I. Madero', 'Huasca de Ocampo',
    'Huautla', 'Huejutla de Reyes', 'Huichapan', 'Ixmiquilpan',
    'Jacala de Ledezma', 'Metztitlán', 'Mineral de la Reforma',
    'Mineral del Monte', 'Mixquiahuala de Juárez', 'Molango de Escamilla',
    'Nopala de Villagrán', 'Pachuca de Soto', 'Progreso de Obregón',
    'San Agustín Tlaxiaca', 'San Felipe Orizatlán', 'San Salvador',
    'Santiago Tulantepec de Lugo Guerrero', 'Tasquillo', 'Tecozautla',
    'Tenango de Doria', 'Tepeapulco', 'Tepeji del Río de Ocampo',
    'Tezontepec de Aldama', 'Tizayuca', 'Tlaxcoapan', 'Tula de Allende',
    'Tulancingo de Bravo', 'Yahualica', 'Zacualtipán de Ángeles',
    'Zapotlán de Juárez', 'Zempoala', 'Zimapán'
  ],
  'Jalisco': [
    'Acatic', 'Acatlán de Juárez', 'Ahualulco de Mercado', 'Ameca',
    'Arandas', 'Atotonilco el Alto', 'Autlán de Navarro', 'Ayotlán',
    'Chapala', 'Cihuatlán', 'Cocula', 'Colotlán', 'Cuautitlán de García Barragán',
    'Degollado', 'El Grullo', 'El Salto', 'Encarnación de Díaz', 'Etzatlán',
    'Guadalajara', 'Hostotipaquillo', 'Ixtlahuacán de los Membrillos',
    'Ixtlahuacán del Río', 'Jalostotitlán', 'Jamay', 'Jocotepec',
    'Juanacatlán', 'La Barca', 'La Huerta', 'Lagos de Moreno', 'Magdalena',
    'Mascota', 'Mazamitla', 'Ocotlán', 'Ojuelos de Jalisco', 'Poncitlán',
    'Puerto Vallarta', 'Purificación', 'Quitupan', 'San Gabriel',
    'San Juan de los Lagos', 'San Julián', 'San Martín Hidalgo',
    'San Miguel el Alto', 'San Pedro Tlaquepaque', 'Sayula',
    'Tamazula de Gordiano', 'Tapalpa', 'Tecolotlán', 'Tenamaxtlán',
    'Teocaltiche', 'Teocuitatlán de Corona', 'Tepatitlán de Morelos',
    'Tequila', 'Teuchitlán', 'Tizapán el Alto', 'Tlajomulco de Zúñiga',
    'Tlaquepaque', 'Tolimán', 'Tomatlán', 'Tonalá', 'Tonaya', 'Tonila',
    'Totatiche', 'Tototlán', 'Tuxcacuesco', 'Tuxcueca', 'Tuxpan',
    'Unión de San Antonio', 'Unión de Tula', 'Valle de Guadalupe',
    'Valle de Juárez', 'Villa Corona', 'Villa Guerrero', 'Villa Hidalgo',
    'Villa Purificación', 'Yahualica de González Gallo', 'Zacoalco de Torres',
    'Zapopan', 'Zapotiltic', 'Zapotitlán de Vadillo', 'Zapotlán del Rey',
    'Zapotlán el Grande', 'Zapotlanejo'
  ],
  'Estado de México': [
    'Acambay de Ruíz Castañeda', 'Acolman', 'Aculco', 'Almoloya de Alquisiras',
    'Almoloya de Juárez', 'Almoloya del Río', 'Amanalco', 'Amatepec',
    'Amecameca', 'Apaxco', 'Atenco', 'Atizapán', 'Atizapán de Zaragoza',
    'Atlacomulco', 'Atlautla', 'Axapusco', 'Ayapango', 'Calimaya',
    'Capulhuac', 'Chalco', 'Chapa de Mota', 'Chapultepec', 'Chiautla',
    'Chicoloapan', 'Chiconcuac', 'Chimalhuacán', 'Coacalco de Berriozábal',
    'Coatepec Harinas', 'Cocotitlán', 'Coyotepec', 'Cuautitlán',
    'Cuautitlán Izcalli', 'Donato Guerra', 'Ecatepec de Morelos',
    'Ecatzingo', 'El Oro', 'Huehuetoca', 'Hueypoxtla', 'Huixquilucan',
    'Isidro Fabela', 'Ixtapaluca', 'Ixtapan de la Sal', 'Ixtapan del Oro',
    'Ixtlahuaca', 'Jaltenco', 'Jilotepec', 'Jilotzingo', 'Jiquipilco',
    'Jocotitlán', 'Joquicingo', 'Juchitepec', 'La Paz', 'Lerma',
    'Luvianos', 'Malinalco', 'Melchor Ocampo', 'Metepec', 'Mexicaltzingo',
    'Morelos', 'Naucalpan de Juárez', 'Netzahualcóyotl', 'Nextlalpan',
    'Nicolás Romero', 'Nopaltepec', 'Ocoyoacac', 'Ocuilan', 'Otumba',
    'Otzoloapan', 'Otzolotepec', 'Ozumba', 'Papalotla', 'Polotitlán',
    'Rayón', 'San Antonio la Isla', 'San Felipe del Progreso',
    'San Martín de las Pirámides', 'San Mateo Atenco', 'San Simón de Guerrero',
    'Santo Tomás', 'Soyaniquilpan de Juárez', 'Sultepec', 'Tecámac',
    'Tejupilco', 'Temamatla', 'Temascalapa', 'Temascalcingo', 'Temascaltepec',
    'Temoaya', 'Tenancingo', 'Tenango del Aire', 'Tenango del Valle',
    'Teoloyucan', 'Teotihuacán', 'Tepetlaoxtoc', 'Tepetlixpa', 'Tepotzotlán',
    'Tequixquiac', 'Texcaltitlán', 'Texcalyacac', 'Texcoco', 'Tezoyuca',
    'Tianguistenco', 'Timilpan', 'Tlalmanalco', 'Tlalnepantla de Baz',
    'Tlatlaya', 'Toluca', 'Tonanitla', 'Tonatico', 'Tultepec', 'Tultitlán',
    'Valle de Bravo', 'Valle de Chalco Solidaridad', 'Villa de Allende',
    'Villa del Carbón', 'Villa Guerrero', 'Villa Victoria', 'Xalatlaco',
    'Xonacatlán', 'Zacazonapan', 'Zacualpan', 'Zinacantepec',
    'Zumpahuacán', 'Zumpango'
  ],
  'Michoacán': [
    'Acuitzio', 'Aguililla', 'Álvaro Obregón', 'Angamacutiro', 'Angangueo',
    'Apatzingán', 'Aporo', 'Aquila', 'Ario', 'Arteaga', 'Briseñas',
    'Buenavista', 'Carácuaro', 'Coahuayana', 'Coalcomán de Vázquez Pallares',
    'Coeneo', 'Contepec', 'Copándaro', 'Cotija', 'Cuitzeo', 'Charapan',
    'Charo', 'Chavinda', 'Cherán', 'Chilchota', 'Chinicuila', 'Chucándiro',
    'Churintzio', 'Churumuco', 'Ecuandureo', 'Epitacio Huerta', 'Erongarícuaro',
    'Gabriel Zamora', 'Hidalgo', 'Huandacareo', 'Huaniqueo', 'Huetamo',
    'Huiramba', 'Indaparapeo', 'Irimbo', 'Ixtlán', 'Jacona', 'Jiménez',
    'Jiquilpan', 'José Sixto Verduzco', 'Juárez', 'Jungapeo', 'La Piedad',
    'Lagunillas', 'Lázaro Cárdenas', 'Los Reyes', 'Madero', 'Maravatío',
    'Marcos Castellanos', 'Morelia', 'Morelos', 'Múgica', 'Nahuatzen',
    'Nocupétaro', 'Nuevo Parangaricutiro', 'Nuevo Urecho', 'Numarán',
    'Ocampo', 'Pajacuarán', 'Panindícuaro', 'Parácuaro', 'Paracho',
    'Pátzcuaro', 'Penjamillo', 'Peribán', 'Purépero', 'Puruarán',
    'Queréndaro', 'Quiroga', 'Régules', 'Sahuayo', 'Salvador Escalante',
    'San Lucas', 'Santa Ana Maya', 'Senguio', 'Susupuato', 'Tacámbaro',
    'Tancítaro', 'Tangamandapio', 'Tangancícuaro', 'Tanhuato', 'Taretan',
    'Tarímbaro', 'Tepalcatepec', 'Tingambato', 'Tingüindín', 'Tiquicheo de Nicolás Romero',
    'Tlalpujahua', 'Tlazazalca', 'Tocumbo', 'Tumbiscatío', 'Turicato',
    'Tuxpan', 'Tuzantla', 'Tzintzuntzan', 'Tzitzio', 'Uruapan',
    'Venustiano Carranza', 'Villamar', 'Vista Hermosa', 'Yurécuaro',
    'Zacapu', 'Zamora', 'Zináparo', 'Zinapécuaro', 'Ziracuaretiro', 'Zitácuaro'
  ],
'Morelos': [
    'Amacuzac', 'Atlatlahucan', 'Axochiapan', 'Ayala', 'Coatlán del Río',
    'Cuautla', 'Cuernavaca', 'Emiliano Zapata', 'Huitzilac', 'Jantetelco',
    'Jiutepec', 'Jojutla', 'Mazatepec', 'Miacatlán', 'Ocuituco',
    'Puente de Ixtla', 'Temixco', 'Tepalcingo', 'Tepoztlán', 'Tetecala',
    'Tlaltizapán de Zapata', 'Tlaquiltenango', 'Tlayacapan', 'Totolapan',
    'Xochitepec', 'Yautepec de Zaragoza', 'Yecapixtla', 'Zacatepec'
  ],
  'Nayarit': [
    'Acaponeta', 'Ahuacatlán', 'Amatlán de Cañas', 'Bahía de Banderas',
    'Compostela', 'Del Nayar', 'Huajicori', 'Ixtlán del Río', 'Jala',
    'La Yesca', 'Rosamorada', 'Ruíz', 'San Blas', 'San Pedro Lagunillas',
    'Santa María del Oro', 'Santiago Ixcuintla', 'Tecuala', 'Tepic',
    'Tuxpan', 'Xalisco'
  ],
  'Nuevo León': [
    'Abasolo', 'Agualeguas', 'Allende', 'Anáhuac', 'Apodaca', 'Aramberri',
    'Bustamante', 'Cadereyta Jiménez', 'Carmen', 'Cerralvo', 'China',
    'Ciénega de Flores', 'Doctor Arroyo', 'Doctor González', 'Galeana',
    'García', 'General Bravo', 'General Escobedo', 'General Terán',
    'General Zuazua', 'Guadalupe', 'Hidalgo', 'Hualahuises', 'Iturbide',
    'Juárez', 'Lampazos de Naranjo', 'Linares', 'Los Herreras', 'Los Ramones',
    'Marín', 'Melchor Ocampo', 'Mier y Noriega', 'Mina', 'Montemorelos',
    'Monterrey', 'Parás', 'Pesquería', 'Rayones', 'Sabinas Hidalgo',
    'Salinas Victoria', 'San Nicolás de los Garza', 'San Pedro Garza García',
    'Santa Catarina', 'Santiago', 'Vallecillo', 'Villaldama'
  ],
  'Oaxaca': [
    'Acatlán de Pérez Figueroa', 'Asunción Nochixtlán', 'Ciudad Ixtepec',
    'Cuicatlán', 'Ejutla de Crespo', 'El Espinal', 'Huajuapan de León',
    'Huautla de Jiménez', 'Ixtlán de Juárez', 'Juchitán de Zaragoza',
    'Loma Bonita', 'Miahuatlán de Porfirio Díaz', 'Mitla', 'Oaxaca de Juárez',
    'Ocotlán de Morelos', 'Pinotepa Nacional', 'Pochutla', 'Puerto Escondido',
    'Putla Villa de Guerrero', 'Salina Cruz', 'San Juan Bautista Tuxtepec',
    'San Juan Bautista Valle Nacional', 'San Pedro Pochutla', 'San Pedro Tapanatepec',
    'Santa Cruz Xoxocotlán', 'Santa Lucía del Camino', 'Santa María Atzompa',
    'Santa María del Tule', 'Santiago Juxtlahuaca', 'Santiago Pinotepa Nacional',
    'Santo Domingo Tehuantepec', 'Tamazulapam del Espíritu Santo',
    'Tehuantepec', 'Tlaxiaco', 'Tlacolula de Matamoros', 'Tuxtepec',
    'Villa de Zaachila', 'Zimatlán de Álvarez'
  ],
  'Puebla': [
    'Acatlán', 'Acatzingo', 'Ajalpan', 'Atlixco', 'Amozoc',
    'Chalchicomula de Sesma', 'Chiautla', 'Chignahuapan', 'Cholula',
    'Coronango', 'Cuautlancingo', 'Cuetzalan del Progreso', 'Esperanza',
    'Huauchinango', 'Huejotzingo', 'Hueytamalco', 'Izúcar de Matamoros',
    'Juan C. Bonilla', 'Libres', 'Nopalucan', 'Oriental', 'Pahuatlán',
    'Palmar de Bravo', 'Puebla', 'Quecholac', 'Rafael Lara Grajales',
    'San Andrés Cholula', 'San Martín Texmelucan', 'San Miguel Xoxtla',
    'San Pedro Cholula', 'San Salvador el Seco', 'San Salvador el Verde',
    'Santa Isabel Cholula', 'Tecali de Herrera', 'Tecamachalco',
    'Tehuacán', 'Tepeaca', 'Teziutlán', 'Tlatlauquitepec', 'Xicotepec',
    'Xochiapulco', 'Yaonáhuac', 'Zacapoaxtla', 'Zacatlán', 'Zinacatepec'
  ],
  'Querétaro': [
    'Amealco de Bonfil', 'Arroyo Seco', 'Cadereyta de Montes', 'Colón',
    'Corregidora', 'El Marqués', 'Ezequiel Montes', 'Huimilpan',
    'Jalpan de Serra', 'Landa de Matamoros', 'Pedro Escobedo',
    'Peñamiller', 'Pinal de Amoles', 'Querétaro', 'San Joaquín',
    'San Juan del Río', 'Tequisquiapan', 'Tolimán'
  ],
  'Quintana Roo': [
    'Bacalar', 'Benito Juárez', 'Cozumel', 'Felipe Carrillo Puerto',
    'Isla Mujeres', 'José María Morelos', 'Lázaro Cárdenas',
    'Othón P. Blanco', 'Puerto Morelos', 'Solidaridad', 'Tulum'
  ],
  'San Luis Potosí': [
    'Ahualulco', 'Alaquines', 'Aquismón', 'Armadillo de los Infante',
    'Cárdenas', 'Catorce', 'Cedral', 'Cerritos', 'Cerro de San Pedro',
    'Ciudad del Maíz', 'Ciudad Fernández', 'Ciudad Valles', 'Coxcatlán',
    'Charcas', 'Ebano', 'El Naranjo', 'Guadalcázar', 'Huehuetlán',
    'Lagunillas', 'Matehuala', 'Matlapa', 'Mexquitic de Carmona',
    'Moctezuma', 'Rayón', 'Rioverde', 'Salinas', 'San Antonio',
    'San Ciro de Acosta', 'San Luis Potosí', 'San Martín Chalchicuautla',
    'San Nicolás Tolentino', 'San Vicente Tancuayalab', 'Santa Catarina',
    'Santa María del Río', 'Santo Domingo', 'Soledad de Graciano Sánchez',
    'Tamasopo', 'Tamazunchale', 'Tampacán', 'Tampamolón Corona',
    'Tamuín', 'Tancanhuitz', 'Tanlajás', 'Tanquián de Escobedo',
    'Tierra Nueva', 'Vanegas', 'Venado', 'Villa de Arriaga',
    'Villa de Arista', 'Villa de Guadalupe', 'Villa de la Paz',
    'Villa de Ramos', 'Villa de Reyes', 'Villa Hidalgo',
    'Villa Juárez', 'Villanueva', 'Xilitla', 'Zaragoza'
  ],
  'Sinaloa': [
    'Ahome', 'Angostura', 'Badiraguato', 'Choix', 'Concordia',
    'Cosalá', 'Culiacán', 'El Fuerte', 'Elota', 'Escuinapa',
    'Guasave', 'Mazatlán', 'Mocorito', 'Navolato', 'Rosario',
    'Salvador Alvarado', 'San Ignacio', 'Sinaloa'
  ],
'Sonora': [
    'Aconchi', 'Agua Prieta', 'Alamos', 'Altar', 'Arivechi', 'Arizpe',
    'Atil', 'Bacadéhuachi', 'Bacanora', 'Bacerac', 'Bacoachi', 'Bácum',
    'Banámichi', 'Baviácora', 'Bavispe', 'Benjamín Hill', 'Caborca',
    'Cajeme', 'Cananea', 'Carbó', 'Cucurpe', 'Cumpas', 'Divisaderos',
    'Empalme', 'Etchojoa', 'Fronteras', 'Granados', 'Guaymas',
    'Hermosillo', 'Huachinera', 'Huásabas', 'Huatabampo', 'Huépac',
    'Imuris', 'La Colorada', 'Magdalena', 'Mazatán', 'Moctezuma',
    'Naco', 'Nácori Chico', 'Nacozari de García', 'Navojoa', 'Nogales',
    'Onavas', 'Opodepe', 'Oquitoa', 'Pitiquito', 'Puerto Peñasco',
    'Quiriego', 'Rayón', 'Rosario', 'Sahuaripa', 'San Felipe de Jesús',
    'San Javier', 'San Luis Río Colorado', 'San Miguel de Horcasitas',
    'San Pedro de la Cueva', 'Santa Ana', 'Santa Cruz', 'Sáric',
    'Soyopa', 'Suaqui Grande', 'Tepache', 'Trincheras', 'Tubutama',
    'Ures', 'Villa Hidalgo', 'Villa Pesqueira', 'Yécora'
  ],
  'Tabasco': [
    'Balancán', 'Cárdenas', 'Centla', 'Centro', 'Comalcalco',
    'Cunduacán', 'Emiliano Zapata', 'Huimanguillo', 'Jalapa',
    'Jalpa de Méndez', 'Jonuta', 'Macuspana', 'Nacajuca', 'Paraíso',
    'Tacotalpa', 'Teapa', 'Tenosique'
  ],
  'Tamaulipas': [
    'Abasolo', 'Aldama', 'Altamira', 'Antiguo Morales', 'Burgos',
    'Bustamante', 'Camargo', 'Casas', 'Ciudad Madero', 'Ciudad Victoria',
    'Cruillas', 'El Mante', 'Gómez Farías', 'González', 'Güémez',
    'Guerrero', 'Gustavo Díaz Ordaz', 'Hidalgo', 'Jaumave', 'Jiménez',
    'Llera', 'Mainero', 'Matamoros', 'Méndez', 'Mier', 'Miguel Alemán',
    'Miquihuana', 'Nuevo Laredo', 'Nuevo Morelos', 'Ocampo', 'Padilla',
    'Palmillas', 'Reynosa', 'Río Bravo', 'San Carlos', 'San Fernando',
    'San Nicolás', 'Soto la Marina', 'Tampico', 'Tula', 'Valle Hermoso',
    'Victoria', 'Villagrán', 'Xicoténcatl'
  ],
  'Tlaxcala': [
    'Acuamanala de Miguel Hidalgo', 'Amaxac de Guerrero', 'Apetatitlán de Antonio Carvajal',
    'Apizaco', 'Atltzayanca', 'Benito Juárez', 'Calpulalpan',
    'Chiautempan', 'Contla de Juan Cuamatzi', 'Cuapiaxtla', 'Cuaxomulco',
    'El Carmen Tequexquitla', 'Emiliano Zapata', 'Español', 'Huamantla',
    'Hueyotlipan', 'Ixtacuixtla de Mariano Matamoros', 'Ixtenco',
    'Lazaro Cardenas', 'Lázaro Cárdenas', 'La Magdalena Tlaltelulco',
    'Mazatecochco de José María Morelos', 'Munoz de Domingo Arenas',
    'Nanacamilpa de Mariano Arista', 'Nativitas', 'Panotla',
    'San Damián Texóloc', 'San Francisco Tetlanohcan', 'San Jerónimo Zacualpan',
    'San José Teacalco', 'San Juan Huactzinco', 'San Lorenzo Axocomanitla',
    'San Lucas Tecopilco', 'San Pablo del Monte', 'Sanctórum de Lázaro Cárdenas',
    'Santa Ana Nopalucan', 'Santa Apolonia Teacalco', 'Santa Catarina Ayometla',
    'Santa Cruz Quilehtla', 'Santa Cruz Tlaxcala', 'Santa Isabel Xiloxoxtla',
    'Tenancingo', 'Teolocholco', 'Tepetitla de Lardizábal', 'Tepeyanco',
    'Terrenate', 'Tetla de la Solidaridad', 'Tetlatlahuca', 'Tlaxcala',
    'Tlaxco', 'Tocatlán', 'Totolac', 'Tzompantepec', 'Xaloztoc',
    'Xaltocan', 'Xicohtzinco', 'Yauhquemehcan', 'Zacatelco', 'Ziltlaltépec de Trinidad Sánchez Santos'
  ],
  'Veracruz': [
    'Acajete', 'Acatlán', 'Acayucan', 'Actopan', 'Agua Dulce',
    'Álamo Temapache', 'Alpatláhuac', 'Alto Lucero de Gutiérrez Barrios',
    'Altotonga', 'Alvarado', 'Amatitlán', 'Amatlán de los Reyes',
    'Ángel R. Cabada', 'Apazapan', 'Aquila', 'Astacinga', 'Atlahuilco',
    'Atoyac', 'Atzacan', 'Atzalan', 'Ayahualulco', 'Banderilla',
    'Benito Juárez', 'Boca del Río', 'Calcahualco', 'Camerino Z. Mendoza',
    'Carrillo Puerto', 'Castillo de Teayo', 'Catemaco', 'Cazones de Herrera',
    'Cerro Azul', 'Chacaltianguis', 'Chalma', 'Chicoasén', 'Chiconquiaco',
    'Chicontepec', 'Chinameca', 'Chinampa de Gorostiza', 'Chocamán',
    'Chontla', 'Chumatlán', 'Citlaltépetl', 'Coahuitlán', 'Coatepec',
    'Coatzacoalcos', 'Coatzintla', 'Coetzala', 'Colipa', 'Comapa',
    'Córdoba', 'Cosamaloapan de Carpio', 'Cosautlán de Carvajal',
    'Coscomatepec', 'Cosoleacaque', 'Cotaxtla', 'Coxquihui', 'Coyutla',
    'Cuichapa', 'Cuitláhuac', 'El Higo', 'Emiliano Zapata', 'Espinal',
    'Filomeno Mata', 'Fortín', 'Gutiérrez Zamora', 'Hidalgotitlán',
    'Huatusco', 'Huayacocotla', 'Hueyapan de Ocampo', 'Huiloapan de Cuauhtémoc',
    'Ignacio de la Llave', 'Ilamatlán', 'Isla', 'Ixcatepec', 'Ixhuacán de los Reyes',
    'Ixhuatlán de Madero', 'Ixhuatlán del Café', 'Ixhuatlán del Sureste',
    'Ixhuatlancillo', 'Ixmatlahuacan', 'Ixtaczoquitlán', 'Jalacingo',
    'Jalcomulco', 'Jáltipan', 'Jamapa', 'Jesús Carranza', 'Jilotepec',
    'José Azueta', 'Juan Rodríguez Clara', 'Juchique de Ferrer',
    'La Antigua', 'La Perla', 'Landero y Coss', 'Las Choapas',
    'Las Minas', 'Las Vigas de Ramírez', 'Lerdo de Tejada', 'Los Reyes',
    'Magdalena', 'Maltrata', 'Manlio Fabio Altamirano', 'Mariano Escobedo',
    'Martínez de la Torre', 'Mecatlán', 'Mecayapan', 'Medellín de Bravo',
    'Miahuatlán', 'Minatitlán', 'Misantla', 'Mixtla de Altamirano',
    'Moloacán', 'Naolinco', 'Naranjal', 'Naranjos Amatlán', 'Nautla',
    'Nogales', 'Oluta', 'Omealca', 'Orizaba', 'Otatitlán', 'Oteapan',
    'Ozuluama de Mascareñas', 'Pajapan', 'Pánuco', 'Papantla',
    'Paso de Ovejas', 'Paso del Macho', 'Perote', 'Platón Sánchez',
    'Playa Vicente', 'Poza Rica de Hidalgo', 'Pueblo Viejo', 'Puente Nacional',
    'Rafael Delgado', 'Rafael Lucio', 'Río Blanco', 'Saltabarranca',
    'San Andrés Tenejapan', 'San Andrés Tuxtla', 'San Juan Evangelista',
    'San Rafael', 'Santiago Sochiapan', 'Santiago Tuxtla', 'Sayula de Alemán',
    'Soconusco', 'Sochiapa', 'Soledad Atzompa', 'Soledad de Doblado',
    'Soteapan', 'Tamalín', 'Tamiahua', 'Tampico Alto', 'Tancoco',
    'Tantima', 'Tantoyuca', 'Tatahuicapan de Juárez', 'Tecolutla',
    'Tehuipango', 'Tempoal', 'Tenampa', 'Tenochtitlán', 'Teocelo',
    'Tepatlaxco', 'Tepetzintla', 'Tepexco', 'Tequila', 'Texcatepec',
    'Texhuacán', 'Texistepec', 'Tezonapa', 'Tihuatlán', 'Tlacojalpan',
    'Tlacolulan', 'Tlacotalpan', 'Tlacotepec de Mejía', 'Tlachichilco',
    'Tlalixcoyan', 'Tlalnelhuayocan', 'Tlaltetela', 'Tlapacoyan',
    'Tlaquilpa', 'Tlilapan', 'Tomatlán', 'Tonayán', 'Totutla',
    'Tuxpan', 'Tuxtilla', 'Úrsulo Galván', 'Uxpanapa', 'Vega de Alatorre',
    'Veracruz', 'Villa Aldama', 'Xalapa', 'Xico', 'Xoxocotla',
    'Yanga', 'Yecuatla', 'Zacualpan', 'Zaragoza', 'Zentla',
    'Zongolica', 'Zontecomatl', 'Zozocolco de Hidalgo'
  ],
  'Yucatán': [
    'Abalá', 'Acanceh', 'Akil', 'Baca', 'Bokobá', 'Buctzotz',
    'Calotmul', 'Cansahcab', 'Cantamayec', 'Celestún', 'Cenotillo',
    'Chacsinkín', 'Chankom', 'Chapab', 'Chemax', 'Chichimilá',
    'Chicxulub Pueblo', 'Chikindzonot', 'Chocholá', 'Chumayel',
    'Conkal', 'Cuncunul', 'Cuzamá', 'Dzán', 'Dzemul', 'Dzidzantún',
    'Dzilam de Bravo', 'Dzilam González', 'Dzitás', 'Dzoncauich',
    'Espita', 'Halachó', 'Hocabá', 'Hoctún', 'Homún', 'Huhí',
    'Hunucmá', 'Ixil', 'Izamal', 'Kanasín', 'Kantunil', 'Kaua',
    'Kinchil', 'Kopomá', 'Mama', 'Maní', 'Maxcanú', 'Mayapán',
    'Mérida', 'Mocochá', 'Motul', 'Muna', 'Muxupip', 'Opichén',
    'Oxkutzcab', 'Panabá', 'Peto', 'Progreso', 'Quintana Roo',
    'Río Lagartos', 'Sacalum', 'Samahil', 'Sanahcat', 'San Felipe',
    'Santa Elena', 'Seyé', 'Sinanché', 'Sotuta', 'Sucilá', 'Sudzal',
    'Suma', 'Supilá', 'Tahdziu', 'Tahmek', 'Teabo', 'Tecoh', 'Tekal de Venegas',
    'Tekantó', 'Tekax', 'Tekit', 'Tekom', 'Telchac Pueblo', 'Telchac Puerto',
    'Temax', 'Temozón', 'Tepakán', 'Tetiz', 'Teya', 'Tical', 'Timucuy',
    'Tinum', 'Tixcacalcupul', 'Tixkokob', 'Tixmehuac', 'Tixpéhual',
    'Tizimín', 'Tzucacab', 'Uayma', 'Ucú', 'Umán', 'Valladolid',
    'Xocchel', 'Yaxcabá', 'Yaxkukul', 'Yobaín'
  ],
  'Zacatecas': [
    'Apozol', 'Apulco', 'Atolinga', 'Benito Juárez', 'Calera',
    'Cañitas de Felipe Pescador', 'Concepción del Oro', 'Cuauhtémoc',
    'El Plateado de Joaquín Amaro', 'El Salvador', 'Fresnillo',
    'Genaro Codina', 'General Enrique Estrada', 'General Francisco R. Murguía',
    'General Pánfilo Natera', 'Guadalupe', 'Huanusco', 'Jalpa',
    'Jerez', 'Jiménez del Teul', 'Juan Aldama', 'Juchipila', 'Loreto',
    'Luis Moya', 'Mazapil', 'Melchor Ocampo', 'Mezquital del Oro',
    'Miguel Auza', 'Momax', 'Monte Escobedo', 'Morelos', 'Moyahua de Estrada',
    'Nochistlán de Mejía', 'Noria de Ángeles', 'Ojocaliente', 'Pánuco',
    'Pinos', 'Río Grande', 'Sain Alto', 'Santa María de la Paz',
    'Sombrerete', 'Susticacán', 'Tabasco', 'Tepechitlán', 'Tepetongo',
    'Teúl de González Ortega', 'Tlaltenango de Sánchez Román',
    'Trancoso', 'Trinidad García de la Cadena', 'Valparaíso',
    'Vetagrande', 'Villa de Cos', 'Villa de García', 'Villa González Ortega',
    'Villa Hidalgo', 'Villanueva', 'Zacatecas'
  ],
}

export const estados = Object.keys(estadosMunicipios).sort()